casir_messenger/urls.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals

from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^403/$', TemplateView.as_view(template_name="403.html")),
                       url(r'^404/$', TemplateView.as_view(template_name="404.html")),
                       url(r'^500/$', TemplateView.as_view(template_name="500.html")),
                       url(r'^503/$', TemplateView.as_view(template_name="503.html")),
                       url(r'^membre/', include("members.urls", namespace="members")),
                       url(r'^dashboard/', include("dashboard.urls", namespace="dashboard")),
                       url(r'', include("promotion.urls", namespace="promotion")),
                       )

if settings.DEBUG:
    # Add the Debug Toolbar's URLs to the project's URLconf
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)),)

    # In DEBUG mode, serve media files through Django.
    urlpatterns += staticfiles_urlpatterns()
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('', url(r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),)

dashboard/urls.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals
from django.conf.urls import patterns, url


urlpatterns = patterns('',
                       url(r'^index/$', 'dashboard.views.index', name="index"),
                       url('^message/(?P<message_pk>\d+)/$', 'dashboard.views.message', name="getMessage"),
                       url(r'^remove/(?P<friend_pk>[\d]+)/$', 'dashboard.views.remove_friend', name="remove"),
                       )

members/urls.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals
from django.conf.urls import patterns, url


urlpatterns = patterns('',
                       url(r'^se-deconnecter/$', 'django.contrib.auth.views.logout', {'next_page': "/"}, name="logout"))

dashboard/forms.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals

dashboard/views.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from members.models import Member
from members.forms import AddFriendForm
from members.forms import PendingRequestForm
from messaging.forms import SendMessageForm
from messaging.models import Message


@login_required
def index(request):
    current_member = request.user.member
    message_form = SendMessageForm(member=current_member)
    add_friend_form = AddFriendForm(member=current_member)
    pending_request_form = PendingRequestForm(member=current_member)
    messages_received = Message.objects.filter(recipient=current_member)
    detail_user = ""
    if request.method == "POST":
        if "add_friend_request" in request.POST:
            add_friend_form = AddFriendForm(member=current_member, data=request.POST)
            pending_request_form = PendingRequestForm(member=current_member)
            if add_friend_form.is_valid():
                for member in add_friend_form.cleaned_data["members"]:
                    member.friend_requests.add(current_member)
                add_friend_form = AddFriendForm(member=current_member)

                messages.success(request, "Demandes d'ajout effectuées avec succès")
        elif "send_message" in request.POST:

            message_form = SendMessageForm(member=current_member, data=request.POST, files=request.FILES)
            if message_form.is_valid():
                Message(author=current_member,
                        recipient=message_form.cleaned_data['recipient'],
                        content=message_form.cleaned_data['content'],
                        duration=message_form.cleaned_data['duration'],
                        picture=message_form.cleaned_data['picture']) \
                    .save()
                message_form = SendMessageForm(member=current_member)

        else:
            pending_request_form = PendingRequestForm(member=current_member, data=request.POST)
            add_friend_form = AddFriendForm(member=current_member)
            if pending_request_form.is_valid():
                if "refuse_pending_request" in request.POST:
                    for member in pending_request_form.cleaned_data["members"]:
                        current_member.friend_requests.remove(member)
                    messages.success(request, "Demandes en attente refusées avec succès")
                elif "accept_pending_request" in request.POST:
                    for member in pending_request_form.cleaned_data["members"]:
                        current_member.friend_requests.remove(member)
                        current_member.friends.add(member)
                    messages.success(request, "Demandes en attente acceptées avec succès")
            else:
                messages.warning(request, "Demandes en attente : opération annulée")
    elif request.method == "GET":
        add_friend_form = AddFriendForm(member=current_member)
        pending_request_form = PendingRequestForm(member=current_member)
        if "detail_user" in request.GET:
            detail_user = request.GET.get("detail_user")
            if detail_user:
                messages_received = messages_received.filter(author__user__username=detail_user)
        if "numero_page" in request.GET:
            numero_page = request.GET.get("numero_page")

    paginator = Paginator(messages_received, 1)

    list_message = []
    try:
        list_message = paginator.page(numero_page)
    except PageNotAnInteger:
        list_message = paginator.page(1)
    except EmptyPage:
        list_message = paginator.page(paginator.num_pages)
    except UnboundLocalError:
        list_message = paginator.page(1)
    friends = current_member.friends.all()
    friend_requests = current_member.friend_requests.all()
    context = {'friends': friends,
               'friend_requests': friend_requests,
               'add_friend_form': add_friend_form,
               'pending_request_form': pending_request_form,
               'message_form': message_form,
               'messages_received': list_message.object_list,
               'current_page': list_message,
               'detail_user': detail_user,
               'paginator': paginator}

    return render(request, "dashboard/index.html", context)


@login_required
def remove_friend(request, friend_pk):
    current_member = request.user.member
    removed_friend = get_object_or_404(Member, pk=friend_pk)
    current_member.friends.remove(removed_friend)
    messages.success(request, "Suppression effectuée avec succès")
    return redirect("dashboard:index")


@login_required
def message(request, message_pk):
    message = get_object_or_404(Message, pk=message_pk)
    if message.is_read:
        return False

    message.is_read = True
    message.save()
    url_picture = ""
    if message.picture == "":
        url_picture = "/media/no_image.png"
    else:
        url_picture = message.picture.url
    data = {
        'picture': url_picture,
        'content': message.content,
        'duration': message.duration,
        'author': message.author.user.username
    }
    return JsonResponse(data)

dashboard/templates/dashboard/base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extrastyles %}<link href="{% static 'css/dashboard.css' %}" rel="stylesheet">{% endblock %}

{% block content %}

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		{% for message in messages %}
			<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ message }}</div>
		{% endfor %}
	</div>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<div class="jumbotron">
			  <h1>Dashboard</h1>
			  <p>Vous pouvez gérer vos messages et vos amis depuis cet espace !</p>
			</div>
		</div>
	</div>

    {%  block dashboard_inner %}
    {% endblock dashboard_inner %}
</div>
{% endblock content %}

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}

{% block body_id %}id_dashboard_index{% endblock body_id %}

{%  block dashboard_inner %}
<div class="row">
    <div class="col-sm-3 col-md-2">
        <div class="panel panel-default">
            <div class="panel-heading">Mes amis</div>
            <ul class="list-group">
                {% for friend in friends %}
                <li class="list-group-item">
                    <a href="?detail_user={{ friend.user.username }}"
                       title="Voir les détails de {{ friend.user.username }}">{{ friend.user.username }}</a>
                    <a href="{% url 'dashboard:remove' friend_pk=friend.pk %}"
                       title="Supprimer {{ friend.user.username }} de mes amis">
                        <span class="glyphicon glyphicon-remove-circle" aria-hidden="true" style="float: right;"></span>
                    </a>
                </li>
                {% endfor %}
            </ul>

            <div class="panel-body">
                <button type="button" class="btn btn-success btn-block" data-toggle="modal"
                        data-target="#id_add_friend_modal">Ajouter un ami
                </button>
            </div>

        </div>
    </div>

    <div class="col-sm-9 col-md-10">
        <div class="row">
            <div class="col-sm-3 col-md-2">
                <button type="button" class="btn btn-success" title="Nouveau message" data-toggle="modal"
                        data-target="#id_new_message_modal">Nouveau message
                </button>
            </div>
            <div class="col-sm-3 col-md-2">
                <button type="button" class="btn btn-success" title="Demandes en attente" data-toggle="modal"
                        data-target="#id_waiting_friends_modal">Demandes en attente <span class="badge">{{ friend_requests|length }}</span>
                </button>
            </div>
        </div>

        <div class="row" id="id_messages_list_row">
            <div class="col-sm-12">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Pseudo</th>
                        <th>Date</th>
                        <th>Etat</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for message in messages_received %}
                    {% if message.is_read %}
                    <tr class="success" >
                        {% else %}
                    <tr class="danger" onclick="showMessage({{ message.id }})">
                        {% endif %}
                        <td>{{ message.author }}</td>
                        <td>{{ message.created_on }}</td>
                        {% if message.is_read %}
                        <td>Lu</td>
                        {% else %}
                        <td>Non lu</td>
                        {% endif %}

                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <nav class="pull-right">

                    <ul class="pagination">
                        {% if current_page.has_previous %}
                        <li>
                            <a href="{{current_url}}?numero_page={{current_page.previous_page_number}}&detail_user={{ detail_user }}"
                               aria-label="Previous">
                                <span aria-hidden="true"><</span>
                            </a>
                        </li>
                        {% endif %}
                        {% for page in paginator.page_range %}
                        {% if page == list_messages.number %}
                        <li class="active">
                            {% else %}
                        <li>
                            {% endif %}
                            <a href="{{current_url}}?numero_page={{page}}&detail_user={{ detail_user }}">{{page}}</a>
                        </li>
                        {% endfor %}
                        {% if current_page.has_next %}
                        <li>
                            <a href="{{current_url}}?numero_page={{current_page.next_page_number}}&detail_user={{ detail_user }}"
                               aria-label="Next">
                                <span aria-hidden="true">></span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>

                </nav>
            </div>
        </div>
    </div>

    <div class="modal fade" id="id_add_friend_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Ajouter un ami</h4>
                </div>
                <form method='POST' action=".">
                    {% csrf_token %}
                    <div class="modal-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th colspan="2">Pseudo</th>
                            </tr>
                            </thead>
                            {% for friend in add_friend_form.members.field.choices %}
                            <tr>
                                <td class="success">{{ friend.1 }}</td>
                                <td><input type="checkbox" name="{{ add_friend_form.members.html_name }}"
                                           id="id_{{ add_friend_form.members.html_name }}_{{ forloop.counter }}"
                                           value="{{ friend.0 }}"></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success" name="add_friend_request">Envoyer une demande
                            d'ajout
                        </button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div class="modal fade" id="id_waiting_friends_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Demandes d'ajout en attente</h4>
                </div>
                <form method='POST' action=".">
                    {% csrf_token %}
                    <div class="modal-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th colspan="2">Pseudo</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for pending_request in pending_request_form.members.field.choices %}
                            <tr>
                                <td class="success">{{ pending_request.1 }}</td>
                                <td><input type="checkbox" name="{{ pending_request_form.members.html_name }}"
                                           id="id_{{ pending_request_form.members.html_name }}_{{ forloop.counter }}"
                                           value="{{ pending_request.0 }}"></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger" name="refuse_pending_request">Refuser la/les
                            demandes
                        </button>
                        <button type="submit" class="btn btn-success" name="accept_pending_request">Accepter la/les
                            demandes
                        </button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <div class="modal fade" id="id_new_message_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Nouveau Message</h4>
                </div>
                <form method='POST' action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">
                        {% for field in message_form %}
                        <div class="row">
                            <label class="col-lg-3">{{ field.label }} </label>
                            <label class="col-lg-9">{{ field }}</label>
                        </div>
                        {% endfor %}
                        <input type="submit" name="send_message" value="Envoyer message"/>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <div class="modal fade in" id="message_show">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal_title"></h4>
                </div>
                <div class="modal-body">
                    <div class="modal_contenu"></div>
                    <img class="modal_image" />
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

    <script>

    function showMessage(id_message)
    {
        var self = $(this);

        $.ajax('/dashboard/message/' + id_message + '/', {
            dataType: 'json',
            success: function(data){
                $('#message_show .modal_title').html(data.author);
                $('#message_show .modal_contenu').html(data.content);
                $('#message_show .modal_image').attr('src', data.picture);
                $('#message_show').modal('show')
            },
            error: function(arg){
                console.log(arg);
            }
        });
    }

    </script>

    {% endblock dashboard_inner %}